name: llama_benchmark_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==24.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - datasets==3.2.0
      - dill==0.3.8
      - filelock==3.13.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - huggingface-hub==0.27.1
      - idna==3.10
      - intel-extension-for-pytorch==2.4.0
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numpy==2.2.2
      - packaging==24.2
      - pandas==2.2.3
      - propcache==0.2.1
      - psutil==6.1.1
      - pyarrow==19.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - six==1.17.0
      - sympy==1.13.1
      - tokenizers==0.19.1
      - torch==2.4.0+cpu
      - tqdm==4.67.1
      - transformers==4.43.2
      - typing-extensions==4.9.0
      - tzdata==2024.2
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - zentorch==5.0.0
